### PR TITLE
timestamps management : created_at and updated_at

### PR DESCRIPTION
**Pull request by Nwenn**
Respond to https://github.com/Flynsarmy/laravel-csv-seeder/issues/23

### CODE REVIEW

**Comment by Nwenn** [comment]
Oups ! It's a mistake !!!

**Comment by Nwenn** [comment]
Oups ! It's a mistake !!!
Sorry, this is the first time I'm doing a pull request.

(sorry for my English)

**Comment by Flynsarmy** [comment]
One other minor change before I can merge: If created_at or updated_at columns already exist, don't overwrite them. Something like this:
```php
                $new[$key] = $item;
                if ( !isset($new[$key]['created_at']) )
                    $new[$key]['created_at'] = \Carbon\Carbon::now();
                if ( !isset($new[$key]['updated_at']) )
                    $new[$key]['updated_at'] = \Carbon\Carbon::now();
```

Thoughts?

**Comment by Nwenn** [comment]
Why not, but is it worth the cost ? There is already the option to say
whether we add them automatically or not.

>

**Comment by Flynsarmy** [comment]
Added in https://github.com/Flynsarmy/laravel-csv-seeder/commit/92acae3c0eecf9cf35c9ab3a55dc963b96b5a252

**Pull request closed without merging**
