### PR TITLE
Update CsvSeeder.php

### PR DESCRIPTION
**Pull request by mtakahashi1977**
plz fix it.

### CODE REVIEW

**Comment by Flynsarmy** [comment]
What is the purpose of this change and how does it benefit you?

**Comment by mtakahashi1977** [comment]
Carbon :: now ()-> toString (); gives the following error and cannot insert csv.

`[2020-09-19 15:51:46] local.ERROR: CSV insert failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: `

Please let me know if there is another correct solution.

**Comment by Flynsarmy** [comment]
What database are you using? MySQL?

**Comment by mtakahashi1977** [comment]
Yes. MySQL 8.0.

**Comment by gcores** [comment]
I am having the same issue using MySql 5.7

The error shows:
Invalid datetime format: 1292 Incorrect datetime value: 'Fri Oct 02 2020 17:59:39 GMT+0000' for column 'created_at' at row 1 

The error disappears when I set my own created_at and updated_at values.
I also tested doing what @mtakahashi1977 proposes and it looks like the right solution.

**Comment by Flynsarmy** [comment]
If someone could submit a PR that instead replaces `->toString()` with `->toIso8601String()` and update any relevent tests accordingly I'd happily accept. This PR though is unacceptable. I don't want to be passing Carbon objects around in memory.

**Comment by Flynsarmy** [comment]
Have you confirmed this works with your version of MySQL?

**Comment by mtakahashi1977** [comment]
> Have you confirmed this works with your version of MySQL?

$this->created_at = Carbon::now()->toString();
```
$ docker-compose exec -T app php artisan db:seed --class=UsersTableSeeder
[2020-10-03 18:22:11] local.ERROR: CSV insert failed: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'Sat Oct 03 2020 18:22:11 GMT+0900' for column 'created_at' at row 1 
```

$this->created_at = Carbon::now()->toIso8601String();
```
$ docker-compose exec -T app php artisan db:seed --class=UsersTableSeeder
Database seeding completed successfully.
```

**Pull request merged**
